sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "11"

os:
  - osx
  - linux

install:
  - travis_retry yarn install

script:
  - uname -a
  - node --version
  - npm --version
  # linting
  - yarn lint
  # nodejs testing
  - yarn test

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
