environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.12'
    - nodejs_version: '1.0'
    - nodejs_version: '4.2'
    - nodejs_version: '5'
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test
build: off
matrix:
  fast_finish: true
